server:
  port: 8762

spring:
  application:
    name: gateway

zuul:
  routes:
    client:
      path: /client/**
      serviceId: client
    elite:
      path: /elite/**
      serviceId: elite
    config:
      path: /config/**
      serviceId: config

ribbon:
  eureka:
    enabled: true

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

logging:
  level:
    org.springframework.cloud: ERROR
    spring.microservices.cloud.gateway: INFO
  pattern:
    file: "%d{yyyy-MM-dd HH:mm:ss} %-5level - %msg%n"
  file: gateway/src/main/resources/gateway_application.log
