server:
  port: 8762

spring:
  application:
    name: gateway

zuul:
  routes:
    client:
      path: /client/**
      serviceId: client
    elite:
      path: /elite/**
      serviceId: elite
    config:
      path: /config/**
      serviceId: config

ribbon:
  eureka:
    enabled: true

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/