server:
  port: 8762

spring:
  application:
    name: zuul

eureka:
  instance:
    preferIpAddress:
      true
  client:
    registerWithEureka: true
    fetchRegistry: true
  serviceurl:
    defaultzone: http://localhost:8761/eureka/

zuul:
  routes:
    elite:
      path: /elite/**
      serviceId: elite
    client:
      path: /client/**
      serviceId: client
    config:
      path: /config/**
      serviceId: config

ribbon:
  eureka:
    enabled: false
