server:
  port: 8081

spring:
  application:
    name: client
  cloud:
    config:
      uri: http://config

ribbon:
  eureka:
    enabled: true
logging:
  level:
    org.springframework.cloud: ERROR
    spring.microservices.cloud.client: INFO
  pattern:
    file: "%d{yyyy-MM-dd HH:mm:ss} %-5level - %msg%n"
  file: client/src/main/resources/client_application.log



