server:
  port: 8082

spring:
  application:
    name: elite
  cloud:
    config:
      uri: http://config

ribbon:
  eureka:
    enabled: true

logging:
  level:
    org.springframework.cloud: ERROR
    spring.microservices.cloud.elite: INFO
  pattern:
    file: "%d{yyyy-MM-dd HH:mm:ss} %-5level - %msg%n"
  file: elite/src/main/resources/elite_application.log
